# Generated by Django 4.0.3 on 2022-03-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='state',
            field=models.CharField(choices=[('new', 'novo'), ('old', 'velho'), ('uso', 'usado'), ('lixo', 'só o resto')], default='sem info', max_length=4),
        ),
    ]
