# Generated by Django 4.0.3 on 2022-03-29 20:45

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to=books.models.upload_image_books),
        ),
    ]
